server:
  port: 9090
  shutdown: graceful

  # specify main URL for service
  servlet.context-path: /ecohub
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: ${TOMCAT_THREADS_MIN:10}
      max: ${TOMCAT_THREADS_MAX:200}

ecohub:
  domainUrl: https://domain.com

spring:
  application:
    name: ecohub
  lifecycle:
    timeout-per-shutdown-phase: 15s # specify grace period 15 seconds




