server:
  port: 9090
  shutdown: graceful

  # specify main URL for service
  servlet.context-path: /ecohub
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: ${TOMCAT_THREADS_MIN:10}
      max: ${TOMCAT_THREADS_MAX:200}

spring:
  application:
    name: ecohub
  datasource:
    url: jdbc:postgresql://localhost:5432/ecohub
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
      data-source-properties: stringtype=unspecified
  lifecycle:
    timeout-per-shutdown-phase: 15s # specify grace period 15 seconds





